"""Generate seed SQL for the KPI -> Goal edge from the canon workbook.

Source of truth: `CLL_FY2027_Goals_Priorities_Initiatives_and_People.xlsx`,
supplied 2026-10-06 as the most recent canon. Read directly, not retyped.

It emits three things the schema lacked:
  - TeamKPIs.MIId      the canon's stable key (MI-001..MI-029)
  - TeamKPIs.Title     the canon's exact wording (5 differ from what we hold)
  - TeamKPIGoals       the KPI -> Goal edge, parsed from Strategy Alignment

The mapping from the canon's row to our Code is by SOURCE AREA and POSITION
within it, because our codes were built the same way (SOURCE_AREAS index + 1,
dash, within-area sequence). Verified: 24 of 29 names match exactly and the
other 5 are the same work renamed in the same positions.

Run:  python db/build_canon_links.py           # writes db/seed_canon_links.sql
      python db/build_canon_links.py --check   # fail if the output differs
"""
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "seed_canon_links.sql")

WORKBOOK = os.path.join(os.path.expanduser("~"), "Downloads",
                        "CLL_FY2027_Goals_Priorities_Initiatives_and_People.xlsx")


def _sq(s):
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def read_canon(path=WORKBOOK):
    """The Initiatives sheet: [(MI-id, name, source_area, alignment), ...].

    Rows are read in order; the sheet is 100 rows but only the populated ones
    with an MI- id are returned.
    """
    from openpyxl import load_workbook

    wb = load_workbook(path, read_only=True, data_only=True)
    rows = [r for r in wb["Initiatives"].iter_rows(values_only=True)
            if any(v is not None for v in r)]
    out = []
    for r in rows:
        mid = str(r[0] or "").strip()
        if re.match(r"^MI-\d+$", mid):
            out.append((mid, str(r[1] or "").strip(),
                        str(r[2] or "").strip(), str(r[3] or "").strip()))
    return out


def goals_from_alignment(text: str) -> list:
    """The goal numbers an alignment string names.

    'Goal 5' -> [5]; 'Goals 3 + 4 + 5' -> [3,4,5]; 'Goals 1-5' -> [1,2,3,4,5];
    'Goals 1, 2, 3, 4' -> [1,2,3,4]. A range expands.
    """
    text = text or ""
    m = re.search(r"Goals?\s+([\d\s,+\-–]+)", text)
    if not m:
        return []
    span = m.group(1)
    # A range "1-5" or "1–5" expands to every number between.
    rng = re.search(r"(\d)\s*[-–]\s*(\d)", span)
    if rng:
        lo, hi = int(rng.group(1)), int(rng.group(2))
        return list(range(lo, hi + 1))
    return sorted({int(n) for n in re.findall(r"\d", span)})


def build(path=WORKBOOK, out=OUT):
    canon = read_canon(path)
    # Our SourceAreas order, to index the areas the way our codes do.
    from openpyxl import load_workbook
    wb = load_workbook(path, read_only=True, data_only=True)
    areas = []
    for r in wb["Initiatives"].iter_rows(values_only=True):
        sa = str(r[2] or "").strip()
        if sa and sa not in areas and r[0] and str(r[0]).startswith("MI-"):
            areas.append(sa)

    seq = {}
    rows = []
    for mid, name, sa, align in canon:
        idx = areas.index(sa) + 1 if sa in areas else 1
        seq[idx] = seq.get(idx, 0) + 1
        code = "%d-%02d" % (idx, seq[idx])
        rows.append({
            "mi_id": mid, "name": name, "source_area": sa,
            "alignment": align, "code": code,
            "goals": goals_from_alignment(align),
        })

    L = ["-- GENERATED by db/build_canon_links.py from",
         "-- CLL_FY2027_Goals_Priorities_Initiatives_and_People.xlsx.",
         "-- Do not hand-edit. Read from the workbook, not retyped.",
         ""]
    L.append("-- The canon's stable key and exact title for each team KPI.")
    for r in rows:
        L.append("UPDATE TeamKPIs SET MIId=%s, Title=%s WHERE Code=%s;"
                 % (_sq(r["mi_id"]), _sq(r["name"]), _sq(r["code"])))
    L.append("")
    L.append("-- The KPI -> Goal edge, parsed from each alignment string.")
    L.append("INSERT INTO TeamKPIGoals (KPIID, GoalID) VALUES")
    vals = []
    for r in rows:
        for g in r["goals"]:
            vals.append("  ((SELECT KPIID FROM TeamKPIs WHERE Code=%s), "
                        "(SELECT GoalID FROM Goals WHERE GoalNumber=%d))"
                        % (_sq(r["code"]), g))
    L.append(",\n".join(vals) + ";")
    L.append("")

    text = "\n".join(L)
    if "--check" in sys.argv:
        current = io.open(out, encoding="utf-8").read() if os.path.exists(out) else ""
        if current != text:
            print("seed_canon_links.sql is STALE; re-run without --check")
            return 1
        print("seed_canon_links.sql is current (%d KPI rows, %d goal links)"
              % (len(rows), len(vals)))
        return 0

    io.open(out, "w", encoding="utf-8", newline="\n").write(text)
    print("wrote %s" % out)
    print("  KPI rows: %d | goal links: %d" % (len(rows), len(vals)))
    return 0


if __name__ == "__main__":
    raise SystemExit(build())
