"""The October 16 deliverable: the Dean's dashboard, Option A.

GENERATED by scripts/build_oct16_data.py. Do not hand-edit: a rebuild
overwrites this file. Change the generator, or pass --owners.

CONFIRMED: built WITHOUT an owners file. Every figure is illustrative
and no owner is named, which the page states.

Option A was chosen 2026-10-07. Static by design: the brief for this view
says "Static, clickable pages; no live data feeds".
"""

# Whether these figures are confirmed by their owners. Derived from how
# this module was built, never set by hand and never an app setting, so a
# redeploy or a data swap cannot leave the marker wrong.
CONFIRMED = False

DATA_STATUS_ILLUSTRATIVE = "Illustrative \u2014 format only, not CLL results"
DATA_STATUS_CONFIRMED = "Confirmed by each owner"


def data_status() -> str:
    """The marker text, chosen from how this module was built.

    Reports a PARTIAL state rather than rounding to confirmed. A page where
    some owners are named and others are not must not claim the whole is
    confirmed - the confirmed-data spec requires the service to distinguish
    them rather than mark the dataset one way.
    """
    if not CONFIRMED:
        return DATA_STATUS_ILLUSTRATIVE
    named = sum(1 for o in OUTCOMES if owner_is_confirmed(o["owner"]))
    if named == len(OUTCOMES):
        return DATA_STATUS_CONFIRMED
    return "Partly confirmed \u2014 %d of %d owners named" % (named, len(OUTCOMES))


# Three owner states. A withheld name is a marked placeholder and is never
# treated as a confirmed owner.
OWNER_WITHHELD = "[owner withheld]"
OWNER_NONE = "[no owner named]"


def owner_label(owner) -> str:
    """How to show an owner position."""
    return OWNER_NONE if owner is None else owner


def owner_is_confirmed(owner) -> bool:
    """A withheld or missing owner is not a confirmed owner."""
    return bool(owner) and owner != OWNER_WITHHELD


# How an outcome's progress is shown. The page previously computed this in
# its template, so the bar's meaning lived in the view while this module
# documented it as derived. It lives here now, and the template renders
# the value it is handed (the oct16-deliverable spec, design D5).
def percent(outcome) -> int:
    """Milestones reached as a whole percent of those planned, floored.

    Floored, not rounded: a bar that reads 50% when fewer than half the
    milestones are reached would overstate progress, and this page exists
    to not do that.
    """
    planned = outcome["planned"] or 0
    if planned <= 0:
        return 0
    return (100 * outcome["reached"]) // planned


# Page furniture, from the wireframes.
EYEBROW = "OCTOBER 16 \u00b7 THE DEAN'S DASHBOARD"
TITLE = "The Dean's six Blueprint outcomes"
SUBTITLE = "Each outcome shown by milestones reached, until its KPIs have data"
EXPLAINER = (
    "Built on P01\u2013P06 from the Blueprint for 2027. Progress = milestones "
    "reached of milestones planned, reported by each owner."
)
AS_OF = None  # set at the data cutoff when confirmed

SOURCE_NOTE = (
    "Outcomes, headings and the scope figures: the October 16 wireframes, "
    "Option A. The data-requirements table: Oct16_Wireframe_Data_Lists.xlsx, "
    "'Option A Data'. Outcome names and target wording also appear in the CLL "
    "KPI Atomic Definitions Master, Metrics sheet, which the wireframes cite "
    "as their source for target text."
)

# What this view collects by October 16.
SCOPE = [
    ('Data elements', '19', 'on this wireframe'),
    ('Required for Oct 16', '16', 'none deferred'),
    ('In hand now', '8 of 16', '2 partial, 6 not collected'),
    ('Items to collect', '20–30', 'milestones, status from owners'),
    ('People to ask', '4', 'team leads, for owners, dates and status'),
    ('Realistic by Oct 16?', 'Yes', 'if scoped down'),
]

# Both sides, so a reader can decide from the page.
TRADE_OFFS = [
    (True, "Uses the Dean's own framing from the Blueprint"),
    (True, 'Milestone counts are honest: no invented composite scores'),
    (True, 'Grows into the full KPI dashboard later'),
    (False, 'Does not match the 2026 priorities presented in May'),
    (False, 'Needs about 25 milestone updates from owners in one week'),
]

OUTCOMES = [
    {
        "id": 'P01',
        "name": 'One Shared Identity',
        "status": 'On track',
        "reached": 1,
        "planned": 3,
        "summary": 'All 4 teams adopt the message architecture by Q2; 90% of assets aligned by Q4',
        "owner": None,
        "updated": None,
        "milestones": [
            ('Message architecture approved', 'Met'),
            ('Teams adopted (1 of 4)', 'In progress'),
            ('First asset audit', 'Not started'),
        ],
    },
    {
        "id": 'P02',
        "name": 'Champion Innovation',
        "status": 'On track',
        "reached": 2,
        "planned": 3,
        "summary": '6 priority pilots; 3 scale, adapt or stop decisions',
        "owner": None,
        "updated": None,
        "milestones": [
            ('RDI baseline complete', 'Met'),
            ('Innovation call launched', 'Met'),
            ('First stage-gate decisions', 'Due Dec'),
        ],
    },
    {
        "id": 'P03',
        "name": 'Integrated Portfolio & Pathways',
        "status": 'At risk',
        "reached": 1,
        "planned": 3,
        "summary": '2 badged pathways; all new programs mapped; one approval workflow by Q2',
        "owner": None,
        "updated": None,
        "milestones": [
            ('Unified approval process', 'In progress'),
            ('First badged pathway', 'In progress'),
            ('Mapping rule approved', 'Met'),
        ],
    },
    {
        "id": 'P04',
        "name": 'Quality at Scale',
        "status": 'At risk',
        "reached": 0,
        "planned": 3,
        "summary": '20% content reuse; 28-day builds; quality standard on all scaled offerings',
        "owner": None,
        "updated": None,
        "milestones": [
            ('Quality standard approved', 'Not started'),
            ('Reuse baseline', 'In progress'),
            ('Build-time baseline', 'Not started'),
        ],
    },
    {
        "id": 'P05',
        "name": 'Data-Informed Action',
        "status": 'On track',
        "reached": 1,
        "planned": 3,
        "summary": '5 dashboards by Q2; every KPI owned; monthly reviews',
        "owner": None,
        "updated": None,
        "milestones": [
            ('KPI definitions drafted', 'Met'),
            ('College dashboard', 'In progress'),
            ('Owners named', 'Not started'),
        ],
    },
    {
        "id": 'P06',
        "name": 'Culture & Learning',
        "status": 'On track',
        "reached": 1,
        "planned": 3,
        "summary": 'Operating models tested; quarterly learning reviews; 90% of commitments current',
        "owner": None,
        "updated": None,
        "milestones": [
            ('Target structure approved', 'Confirm'),
            ('Q1 learning reviews', 'In progress'),
            ('Operating model template', 'Met'),
        ],
    },
]

# The full 'what it takes to show this on October 16' table: one row per
# data element, with where it comes from and whether we have it. Read from
# the wireframe's own workbook rather than retyped, so the page and the
# workbook cannot drift apart.
DATA_REQUIREMENTS = [
    {
        'id': 'A-01',
        'section': 'Page',
        'element': 'As-of date',
        'definition': 'Date the data was last confirmed',
        'example': 'Oct 13, 2026',
        'volume': '1',
        'source': 'Build team',
        'provided_by': 'Associate Director',
        'available': 'Build',
        'how': 'Set at data cutoff',
        'needed': 'Required',
    },
    {
        'id': 'A-02',
        'section': 'Outcome cards',
        'element': 'Outcome code and name',
        'definition': 'The six Dean outcomes from the Blueprint for 2027',
        'example': 'P03 · Integrated Portfolio & Pathways',
        'volume': '6',
        'source': "Dean's Blueprint (prototype site)",
        'provided_by': 'Build team',
        'available': 'Have it',
        'how': 'Copy from Blueprint',
        'needed': 'Required',
    },
    {
        'id': 'A-03',
        'section': 'Outcome cards',
        'element': 'Outcome target',
        'definition': 'Blueprint target wording for each outcome',
        'example': '2 badged pathways; all new programs mapped; one approval workflow by Q2',
        'volume': '6',
        'source': "Dean's Blueprint; KPI definitions doc",
        'provided_by': 'Build team',
        'available': 'Have it',
        'how': 'Copy from Blueprint',
        'needed': 'Required',
    },
    {
        'id': 'A-04',
        'section': 'Outcome cards',
        'element': 'Outcome owner',
        'definition': 'Named person accountable for the outcome',
        'example': '[name]',
        'volume': '6',
        'source': 'Dean; team leads',
        'provided_by': 'Elizabeth / Dean',
        'available': 'No',
        'how': "Ask at the Dean's pick meeting",
        'needed': 'Required',
    },
    {
        'id': 'A-05',
        'section': 'Outcome cards',
        'element': 'Outcome status',
        'definition': 'On track, At risk, Behind, or Not started; owner judgment, confirmed by the team lead',
        'example': 'At risk',
        'volume': '6',
        'source': 'Outcome owners',
        'provided_by': 'Team leads',
        'available': 'No',
        'how': 'Team-lead confirmation session (30 min)',
        'needed': 'Required',
    },
    {
        'id': 'A-06',
        'section': 'Outcome cards',
        'element': 'Last-updated date',
        'definition': "When each outcome's status was last confirmed",
        'example': 'Oct 13, 2026',
        'volume': '6',
        'source': 'Outcome owners',
        'provided_by': 'Team leads',
        'available': 'No',
        'how': 'Recorded in the confirmation session',
        'needed': 'Required',
    },
    {
        'id': 'A-07',
        'section': 'Milestones',
        'element': 'Milestone ID',
        'definition': 'Stable ID for each milestone',
        'example': 'P03-M2',
        'volume': '18–30',
        'source': 'Build team',
        'provided_by': 'Associate Director',
        'available': 'Build',
        'how': 'Assigned when the list is drafted',
        'needed': 'Required',
    },
    {
        'id': 'A-08',
        'section': 'Milestones',
        'element': 'Milestone name',
        'definition': 'A concrete, checkable event (approval, launch, first delivery), not an activity',
        'example': 'Unified approval process launched',
        'volume': '18–30 (3–5 per outcome)',
        'source': 'KPI definitions (milestone components); Blueprint targets',
        'provided_by': 'Build team drafts; team leads confirm',
        'available': 'Partial',
        'how': 'Draft from definitions (EXP-05a, EXP-07a, INF-03a, INF-07a, FUT-01a…), confirm with team leads',
        'needed': 'Required',
    },
    {
        'id': 'A-09',
        'section': 'Milestones',
        'element': 'Linked outcome',
        'definition': 'Which Dean outcome the milestone counts toward',
        'example': 'P03',
        'volume': '18–30',
        'source': 'Crosswalk; KPI definitions',
        'provided_by': 'Build team',
        'available': 'Have it',
        'how': 'From the Blueprint cascade (primary priority)',
        'needed': 'Required',
    },
    {
        'id': 'A-10',
        'section': 'Milestones',
        'element': 'Linked KPI component',
        'definition': 'Team KPI component the milestone evidences, if any',
        'example': 'EXP-07a',
        'volume': '18–30',
        'source': 'KPI definitions workbook, Components tab',
        'provided_by': 'Build team',
        'available': 'Have it',
        'how': 'Lookup',
        'needed': 'Optional',
    },
    {
        'id': 'A-11',
        'section': 'Milestones',
        'element': 'Planned date',
        'definition': 'Date the milestone is due',
        'example': 'Dec 31, 2026',
        'volume': '18–30',
        'source': 'Blueprint quarter deadlines; owners',
        'provided_by': 'Team leads',
        'available': 'Partial',
        'how': 'Blueprint gives quarters for some; owners set the rest',
        'needed': 'Required',
    },
    {
        'id': 'A-12',
        'section': 'Milestones',
        'element': 'Milestone owner',
        'definition': 'Person responsible for the milestone',
        'example': '[name]',
        'volume': '18–30',
        'source': 'Team leads',
        'provided_by': 'Team leads',
        'available': 'No',
        'how': 'Confirmation session',
        'needed': 'Required',
    },
    {
        'id': 'A-13',
        'section': 'Milestones',
        'element': 'Milestone status',
        'definition': 'Met, In progress, Not started, or Missed',
        'example': 'In progress',
        'volume': '18–30',
        'source': 'Milestone owners',
        'provided_by': 'Team leads',
        'available': 'No',
        'how': 'Confirmation session; self-reported',
        'needed': 'Required',
    },
    {
        'id': 'A-14',
        'section': 'Milestones',
        'element': 'Date met',
        'definition': 'Date the milestone was achieved',
        'example': 'Sep 18, 2026',
        'volume': 'Met milestones only',
        'source': 'Milestone owners',
        'provided_by': 'Team leads',
        'available': 'No',
        'how': 'Confirmation session',
        'needed': 'Required',
    },
    {
        'id': 'A-15',
        'section': 'Milestones',
        'element': 'Evidence link',
        'definition': 'Link to the approving document, minutes, or release note',
        'example': 'SharePoint URL',
        'volume': 'Met milestones only',
        'source': 'Milestone Evidence Register (to build)',
        'provided_by': 'Milestone owners',
        'available': 'No',
        'how': 'Collect links; register built in Stage 2',
        'needed': 'Optional',
    },
    {
        'id': 'A-16',
        'section': 'Outcome cards',
        'element': 'Milestones reached / planned',
        'definition': 'Count of Met milestones over all milestones for the outcome',
        'example': '1 of 4',
        'volume': '6',
        'source': 'Calculated',
        'provided_by': 'Build team',
        'available': 'Derived',
        'how': 'Formula',
        'needed': 'Required',
    },
    {
        'id': 'A-17',
        'section': 'Outcome cards',
        'element': 'Progress bar',
        'definition': 'Milestones reached / planned, as a percent',
        'example': '25%',
        'volume': '6',
        'source': 'Calculated',
        'provided_by': 'Build team',
        'available': 'Derived',
        'how': 'Formula',
        'needed': 'Required',
    },
    {
        'id': 'A-18',
        'section': 'Outcome cards',
        'element': 'Existing initiative % complete (optional context)',
        'definition': 'Percent complete for the 11 existing initiatives listed in the Blueprint',
        'example': 'GT Infinity 2.0 Public · 10%',
        'volume': '11',
        'source': "Dean's Blueprint (prototype site)",
        'provided_by': 'Build team',
        'available': 'Have it',
        'how': 'Copy from Blueprint; ask owners to confirm',
        'needed': 'Optional',
    },
    {
        'id': 'A-19',
        'section': 'Needs panel',
        'element': 'Data availability flags',
        'definition': 'Have it / No for each data row on the board',
        'example': 'No',
        'volume': '5',
        'source': 'This list',
        'provided_by': 'Build team',
        'available': 'Derived',
        'how': 'From this sheet',
        'needed': 'Required',
    },
]
