"""Generate db/seed_rev2.sql: the Rev2 seed, translated from the app's SQLite data.

    python db/build_rev2_seed.py            # writes db/seed_rev2.sql
    python db/build_rev2_seed.py --check    # fail if the output differs

The app's model and Rev2 are different shapes, so this is a translation, not a
copy:

    Goals (5)                 -> goal
    Priorities (6)            -> priority_definition + annual_priority (FY2027)
    Teams (4)                 -> team
    People (11)               -> person
    29 Team Initiatives       -> initiative (initiative_level='D-1')
    11 Dean Initiatives       -> initiative (initiative_level='Dean')
    TeamInitiativeGoals       -> initiative_goal
    TeamInitiativePriorities  -> initiative_priority
    TeamInitiatives.OwnerID   -> initiative_owner (Reporting Owner, primary)
    TeamInitiativeCoOwners    -> initiative_owner (Contributor)
    TeamInitiativeDeanLinks   -> initiative_relationship (Supports, D-1 -> Dean)
    TeamInitiativeUpdates     -> initiative_update (append-only)

Order matters for the cardinality triggers (003): a mapping must exist before an
initiative is Activated. This seed inserts everything as Proposed/Active in an
order that satisfies K1/K2, and keeps the app's "no progress yet" semantics
(Proposed == the app's "Not started").
"""
import io
import os
import sqlite3
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "seed_rev2.sql")
DB = os.environ.get("DB_PATH", os.path.join(HERE, "..", "cll_initiatives.db"))

SOURCE_ID = "SRC-CLL-REGISTER"
EFFECTIVE = "2026-10-07"
PERIOD = "FY2027"

# The app's initiative status -> Rev2 lifecycle (initiative.status).
# 'Not started' (the app's default, no diary) is Rev2 'Proposed'.
def lifecycle(status):
    return {
        "Not started": "Proposed",
        "On track": "Active",
        "At risk": "Active",
        "Off track": "Active",
        "Complete": "Completed",
        "Paused": "On Hold",
    }.get(status or "Not started", "Proposed")


def _s(v):
    if v is None:
        return "NULL"
    return "N'" + str(v).replace("'", "''") + "'"


def _d(v):
    return "NULL" if not v else "'" + str(v) + "'"


def build(out=OUT):
    con = sqlite3.connect(DB)
    con.row_factory = sqlite3.Row

    L = ["-- GENERATED by db/build_rev2_seed.py from the app's cll_initiatives.db.",
         "-- The Rev2 translation. Do not hand-edit.",
         "SET NOCOUNT ON;", "GO", ""]

    # source_record
    L.append("-- Provenance source.")
    L.append("IF NOT EXISTS (SELECT 1 FROM dbo.source_record WHERE source_id = %s)" % _s(SOURCE_ID))
    L.append("INSERT INTO dbo.source_record (source_id, source_type, source_name, authority_level)")
    L.append("VALUES (%s, 'Register', 'Initiative Dashboard Register', 'Canonical');" % _s(SOURCE_ID))
    L.append("GO")

    # goal
    L.append("\n-- Goals (Strategy 2035).")
    for g in con.execute("SELECT GoalNumber, ShortName, FullName, Description FROM Goals ORDER BY GoalNumber"):
        gid = "GOAL-%d" % g["GoalNumber"]
        L.append("IF NOT EXISTS (SELECT 1 FROM dbo.goal WHERE goal_id = %s)" % _s(gid))
        L.append("INSERT INTO dbo.goal (goal_id, goal_number, short_label, canonical_title, "
                 "canonical_description, source_id, display_order) VALUES "
                 "(%s, %d, %s, %s, %s, %s, %d);"
                 % (_s(gid), g["GoalNumber"], _s(g["ShortName"]), _s(g["FullName"]),
                    _s(g["Description"]), _s(SOURCE_ID), g["GoalNumber"]))
    L.append("GO")

    # priority_definition + annual_priority
    L.append("\n-- Priorities: definition (reusable) + annual instance (FY2027).")
    for p in con.execute("SELECT Code, PriorityName, FullTitle, Description, PlanYear FROM Priorities "
                         "WHERE Code IS NOT NULL ORDER BY Code"):
        pdef = "PDEF-" + p["Code"]
        apri = "PRI-%s-%s" % (p["Code"], PERIOD)
        name = p["FullTitle"] or p["PriorityName"]
        L.append("IF NOT EXISTS (SELECT 1 FROM dbo.priority_definition WHERE priority_id = %s)" % _s(pdef))
        L.append("INSERT INTO dbo.priority_definition (priority_id, priority_code, priority_name) VALUES "
                 "(%s, %s, %s);" % (_s(pdef), _s(p["Code"]), _s(name)))
        L.append("IF NOT EXISTS (SELECT 1 FROM dbo.annual_priority WHERE priority_id = %s)" % _s(apri))
        L.append("INSERT INTO dbo.annual_priority (priority_id, priority_code, priority_name, "
                 "description, planning_period, source_id, display_order) VALUES "
                 "(%s, %s, %s, %s, %s, %s, %d);"
                 % (_s(apri), _s(p["Code"]), _s(name), _s(p["Description"]),
                    _s(PERIOD), _s(SOURCE_ID), int(p["Code"][1:])))
    L.append("GO")

    # team
    L.append("\n-- Teams.")
    for t in con.execute("SELECT TeamID, Name, Description FROM Teams ORDER BY TeamID"):
        tid = "TEAM-%d" % t["TeamID"]
        L.append("IF NOT EXISTS (SELECT 1 FROM dbo.team WHERE team_id = %s)" % _s(tid))
        L.append("INSERT INTO dbo.team (team_id, team_name, description) VALUES (%s, %s, %s);"
                 % (_s(tid), _s(t["Name"]), _s(t["Description"])))
    L.append("GO")

    # person
    L.append("\n-- People.")
    for p in con.execute("SELECT PersonID, Name, Title, Email, TeamID FROM People ORDER BY PersonID"):
        pid = "PERS-%d" % p["PersonID"]
        team = "(SELECT team_id FROM dbo.team WHERE team_id = %s)" % _s("TEAM-%d" % p["TeamID"]) if p["TeamID"] else "NULL"
        L.append("IF NOT EXISTS (SELECT 1 FROM dbo.person WHERE person_id = %s)" % _s(pid))
        L.append("INSERT INTO dbo.person (person_id, display_name, business_email, working_title, team_id) "
                 "VALUES (%s, %s, %s, %s, %s);"
                 % (_s(pid), _s(p["Name"]), _s(p["Email"]), _s(p["Title"]), team))
    L.append("GO")

    # initiative: Dean (11) and D-1 (29).
    # ALL are inserted Proposed (or Completed for FY26), because Rev2's K1 rule
    # refuses an Active initiative with no current goal mapping. Mappings and
    # links are added below, then the Active ones are activated.
    L.append("\n-- Dean initiatives (initiative_level='Dean'). FY26 Complete, FY27 in flight.")
    for d in con.execute("SELECT DeanInitiativeID, Code, Title, Description, PercentComplete, FiscalYear "
                         "FROM DeanInitiatives ORDER BY Code"):
        iid = "INI-" + d["Code"]
        # FY26 is complete; FY27 starts Proposed and is activated below.
        st = "Completed" if d["FiscalYear"] == 26 else "Proposed"
        L.append("IF NOT EXISTS (SELECT 1 FROM dbo.initiative WHERE initiative_id = %s)" % _s(iid))
        L.append("INSERT INTO dbo.initiative (initiative_id, initiative_code, initiative_name, description, "
                 "initiative_level, initiative_type, status, progress_value, progress_method, source_id) VALUES "
                 "(%s, %s, %s, %s, 'Dean', 'Initiative', %s, %s, 'Owner Estimate', %s);"
                 % (_s(iid), _s(d["Code"]), _s(d["Title"]), _s(d["Description"] or d["Title"]),
                    _s(st), d["PercentComplete"], _s(SOURCE_ID)))
    L.append("GO")

    # D-1 (Team Initiatives): insert as Proposed FIRST (so no K1/K2 yet), map, then Activate.
    L.append("\n-- Team Initiatives (initiative_level='D-1'). Inserted Proposed; mappings below; then activated.")
    for k in con.execute("SELECT MIId, Code, Title, Description, Status FROM TeamInitiatives "
                         "WHERE IsActive = 1 ORDER BY MIId"):
        iid = "INI-" + (k["MIId"] or k["Code"])
        L.append("IF NOT EXISTS (SELECT 1 FROM dbo.initiative WHERE initiative_id = %s)" % _s(iid))
        L.append("INSERT INTO dbo.initiative (initiative_id, initiative_code, initiative_name, description, "
                 "initiative_level, initiative_type, status, source_id) VALUES "
                 "(%s, %s, %s, %s, 'D-1', 'Initiative', 'Proposed', %s);"
                 % (_s(iid), _s(k["MIId"] or k["Code"]), _s(k["Title"]),
                    _s(k["Description"] or k["Title"]), _s(SOURCE_ID)))
    L.append("GO")

    # initiative_goal (D-1 -> goal)
    L.append("\n-- Team Initiative -> Goal mappings.")
    for r in con.execute(
            "SELECT k.MIId, k.Code, g.GoalNumber FROM TeamInitiativeGoals tg "
            "JOIN TeamInitiatives k ON k.TeamInitiativeID = tg.TeamInitiativeID "
            "JOIN Goals g ON g.GoalID = tg.GoalID WHERE k.IsActive = 1"):
        iid = "INI-" + (r["MIId"] or r["Code"])
        L.append("IF NOT EXISTS (SELECT 1 FROM dbo.initiative_goal WHERE initiative_id = %s AND goal_id = %s)"
                 % (_s(iid), _s("GOAL-%d" % r["GoalNumber"])))
        L.append("INSERT INTO dbo.initiative_goal (initiative_id, goal_id, relationship_type, validation_status, "
                 "effective_start) VALUES (%s, %s, 'Primary', 'Validated', '2026-10-07');"
                 % (_s(iid), _s("GOAL-%d" % r["GoalNumber"])))
    L.append("GO")

    # Dean -> goal, DERIVED from the goals its child D-1 initiatives carry.
    # Rev2's K1 requires every Active initiative to map to a goal; the app's Dean
    # layer links to Priorities, not Goals, so the Dean row has no goal of its own.
    # Giving it the union of its children's goals keeps it Active and honest.
    L.append("\n-- Dean -> Goal, derived from the Dean's child initiatives (K1).")
    dean_goals = {}
    for r in con.execute(
            "SELECT d.Code AS DCode, g.GoalNumber FROM TeamInitiativeDeanLinks kl "
            "JOIN DeanInitiatives d ON d.DeanInitiativeID = kl.DeanInitiativeID "
            "JOIN TeamInitiatives k ON k.TeamInitiativeID = kl.TeamInitiativeID "
            "JOIN TeamInitiativeGoals tg ON tg.TeamInitiativeID = k.TeamInitiativeID "
            "JOIN Goals g ON g.GoalID = tg.GoalID WHERE k.IsActive = 1"):
        dean_goals.setdefault(r["DCode"], set()).add(r["GoalNumber"])
    for dcode, goals in sorted(dean_goals.items()):
        for gn in sorted(goals):
            iid = "INI-" + dcode
            gid = "GOAL-%d" % gn
            L.append("IF NOT EXISTS (SELECT 1 FROM dbo.initiative_goal WHERE initiative_id = %s AND goal_id = %s)"
                     % (_s(iid), _s(gid)))
            L.append("INSERT INTO dbo.initiative_goal (initiative_id, goal_id, relationship_type, "
                     "validation_status, effective_start) VALUES (%s, %s, 'Secondary', 'Validated', '2026-10-07');"
                     % (_s(iid), _s(gid)))
    L.append("GO")
    L.append("\n-- Initiative -> Priority mappings.")
    for r in con.execute(
            "SELECT k.MIId, k.Code, p.Code AS PCode, tp.IsPrimary FROM TeamInitiativePriorities tp "
            "JOIN TeamInitiatives k ON k.TeamInitiativeID = tp.TeamInitiativeID "
            "JOIN Priorities p ON p.PriorityID = tp.PriorityID WHERE k.IsActive = 1"):
        iid = "INI-" + (r["MIId"] or r["Code"])
        rel = "Primary" if r["IsPrimary"] else "Supporting"
        apri = "PRI-%s-%s" % (r["PCode"], PERIOD)
        L.append("IF NOT EXISTS (SELECT 1 FROM dbo.initiative_priority WHERE initiative_id = %s AND priority_id = %s)"
                 % (_s(iid), _s(apri)))
        L.append("INSERT INTO dbo.initiative_priority (initiative_id, priority_id, relationship_type, "
                 "validation_status, effective_start) VALUES (%s, %s, %s, 'Validated', '2026-10-07');"
                 % (_s(iid), _s(apri), _s(rel)))
    # Dean -> priority (each Dean initiative names a PriorityID)
    for d in con.execute(
            "SELECT d.Code, p.Code AS PCode FROM DeanInitiatives d "
            "LEFT JOIN Priorities p ON p.PriorityID = d.PriorityID WHERE p.Code IS NOT NULL"):
        iid = "INI-" + d["Code"]
        apri = "PRI-%s-%s" % (d["PCode"], PERIOD)
        L.append("IF NOT EXISTS (SELECT 1 FROM dbo.initiative_priority WHERE initiative_id = %s AND priority_id = %s)"
                 % (_s(iid), _s(apri)))
        L.append("INSERT INTO dbo.initiative_priority (initiative_id, priority_id, relationship_type, "
                 "validation_status, effective_start) VALUES (%s, %s, 'Primary', 'Validated', '2026-10-07');"
                 % (_s(iid), _s(apri)))
    L.append("GO")

    # initiative_owner (lead = Reporting Owner primary; co-owners = Contributor)
    L.append("\n-- Owners. The lead is Reporting Owner (primary); co-owners are Contributor.")
    for k in con.execute("SELECT k.MIId, k.Code, k.OwnerID FROM TeamInitiatives k "
                         "WHERE k.IsActive = 1 AND k.OwnerID IS NOT NULL"):
        iid = "INI-" + (k["MIId"] or k["Code"])
        lead = "PERS-%d" % k["OwnerID"]
        L.append("IF NOT EXISTS (SELECT 1 FROM dbo.initiative_owner WHERE initiative_id = %s AND person_id = %s "
                 "AND ownership_role = 'Reporting Owner' AND effective_start = '2026-10-07')"
                 % (_s(iid), _s(lead)))
        L.append("INSERT INTO dbo.initiative_owner (initiative_id, person_id, ownership_role, primary_flag, "
                 "effective_start) VALUES (%s, %s, 'Reporting Owner', 1, '2026-10-07');" % (_s(iid), _s(lead)))
    for c in con.execute(
            "SELECT k.MIId, k.Code, co.PersonID FROM TeamInitiativeCoOwners co "
            "JOIN TeamInitiatives k ON k.TeamInitiativeID = co.TeamInitiativeID WHERE k.IsActive = 1"):
        iid = "INI-" + (c["MIId"] or c["Code"])
        pid = "PERS-%d" % c["PersonID"]
        L.append("IF NOT EXISTS (SELECT 1 FROM dbo.initiative_owner WHERE initiative_id = %s AND person_id = %s "
                 "AND ownership_role = 'Contributor' AND effective_start = '2026-10-07')" % (_s(iid), _s(pid)))
        L.append("INSERT INTO dbo.initiative_owner (initiative_id, person_id, ownership_role, primary_flag, "
                 "effective_start) VALUES (%s, %s, 'Contributor', 0, '2026-10-07');" % (_s(iid), _s(pid)))
    L.append("GO")

    # initiative_relationship (D-1 -Supports-> Dean) from TeamInitiativeDeanLinks
    L.append("\n-- D-1 -> Dean links (Supports). Inserted BEFORE activating any D-1 (K2).")
    for r in con.execute(
            "SELECT k.MIId, k.Code, d.Code AS DCode FROM TeamInitiativeDeanLinks kl "
            "JOIN TeamInitiatives k ON k.TeamInitiativeID = kl.TeamInitiativeID "
            "JOIN DeanInitiatives d ON d.DeanInitiativeID = kl.DeanInitiativeID WHERE k.IsActive = 1"):
        fi = "INI-" + (r["MIId"] or r["Code"])
        ti = "INI-" + r["DCode"]
        L.append("IF NOT EXISTS (SELECT 1 FROM dbo.initiative_relationship WHERE from_initiative_id = %s "
                 "AND to_initiative_id = %s AND relationship_type = 'Supports')" % (_s(fi), _s(ti)))
        L.append("INSERT INTO dbo.initiative_relationship (from_initiative_id, to_initiative_id, relationship_type, "
                 "effective_start) VALUES (%s, %s, 'Supports', '2026-10-07');" % (_s(fi), _s(ti)))
    L.append("GO")

    # Now activate the D-1 initiatives whose app status is progress-bearing.
    L.append("\n-- Activate the D-1 initiatives that the app reports as started (K1/K2 satisfied above).")
    for k in con.execute("SELECT MIId, Code, Status FROM TeamInitiatives WHERE IsActive = 1"):
        st = lifecycle(k["Status"])
        if st == "Proposed":
            continue
        iid = "INI-" + (k["MIId"] or k["Code"])
        L.append("UPDATE dbo.initiative SET status = %s WHERE initiative_id = %s AND status = 'Proposed';"
                 % (_s(st), _s(iid)))
    # Activate the FY27 Dean initiatives (their goal mappings now exist).
    L.append("-- Activate the FY27 Dean initiatives (K1 satisfied by the derived goal mappings).")
    for d in con.execute("SELECT Code FROM DeanInitiatives WHERE FiscalYear = 27"):
        L.append("UPDATE dbo.initiative SET status = 'Active' WHERE initiative_id = %s AND status = 'Proposed';"
                 % _s("INI-" + d["Code"]))
    L.append("GO")

    # initiative_update (append-only). The app seed ships none.
    L.append("\n-- Diary (append-only; the app seed ships none).")
    L.append("-- (no initiative_update rows in the committed sample)")
    L.append("GO")

    # -----------------------------------------------------------------------
    # App-layer additions (008_app_layer.sql; change `rev2-full-reconciliation`)
    # -----------------------------------------------------------------------
    L.append("\n-- app_meta: engine-agnostic config (AppMeta).")
    for r in con.execute("SELECT [Key], [Value] FROM AppMeta ORDER BY [Key]"):
        L.append("IF NOT EXISTS (SELECT 1 FROM dbo.app_meta WHERE [key] = %s)" % _s(r["Key"]))
        L.append("INSERT INTO dbo.app_meta ([key], [value]) VALUES (%s, %s);"
                 % (_s(r["Key"]), _s(r["Value"])))
    L.append("GO")

    L.append("\n-- audit_log: schema only (the app seed ships no audit rows).")
    L.append("-- (no audit_log rows in the committed sample)")
    L.append("GO")

    L.append("\n-- role / person_role: the app's role vocabulary (Roles/PeopleRoles),")
    L.append("-- mirrored by NAME because role_id is IDENTITY-generated in Rev2.")
    for r in con.execute("SELECT RoleID, Name, Description FROM Roles ORDER BY RoleID"):
        L.append("IF NOT EXISTS (SELECT 1 FROM dbo.role WHERE name = %s)" % _s(r["Name"]))
        L.append("INSERT INTO dbo.role (name, description) VALUES (%s, %s);"
                 % (_s(r["Name"]), _s(r["Description"])))
    for c in con.execute("SELECT pr.PersonID, ro.Name FROM PeopleRoles pr "
                         "JOIN Roles ro ON ro.RoleID = pr.RoleID ORDER BY pr.PersonID, ro.Name"):
        pid = "PERS-%d" % c["PersonID"]
        rname = c["Name"]
        L.append("IF NOT EXISTS (SELECT 1 FROM dbo.person_role pr "
                 "JOIN dbo.role ro ON ro.role_id = pr.role_id "
                 "WHERE pr.person_id = %s AND ro.name = %s)" % (_s(pid), _s(rname)))
        L.append("INSERT INTO dbo.person_role (person_id, role_id) "
                 "SELECT %s, role_id FROM dbo.role WHERE name = %s;" % (_s(pid), _s(rname)))
    L.append("GO")

    L.append("\n-- source_area: the five source areas.")
    for s in con.execute("SELECT SourceAreaID, Name FROM SourceAreas ORDER BY SourceAreaID"):
        L.append("IF NOT EXISTS (SELECT 1 FROM dbo.source_area WHERE name = %s)" % _s(s["Name"]))
        L.append("INSERT INTO dbo.source_area (name) VALUES (%s);" % _s(s["Name"]))
    L.append("GO")

    # milestone: keyed to the annual_priority instance (PRI-<Code>-FY<year>),
    # resolving the SQLite priority row's (PlanYear, Code) so P01-FY2027's
    # milestones never attach to another year's P01.
    L.append("\n-- milestone: the per-year priority milestones.")
    for m in con.execute(
            "SELECT m.Name, m.Status, m.PlannedDate, m.DateMet, m.OwnerLabel, "
            "       m.EvidenceURL, m.SortOrder, m.IsActive, p.Code, p.PlanYear "
            "FROM Milestones m JOIN Priorities p ON p.PriorityID = m.PriorityID "
            "ORDER BY p.Code, m.SortOrder, m.MilestoneID"):
        apri = "PRI-%s-FY%d" % (m["Code"], m["PlanYear"])
        L.append("IF NOT EXISTS (SELECT 1 FROM dbo.milestone WHERE priority_id = %s AND name = %s)"
                 % (_s(apri), _s(m["Name"])))
        L.append("INSERT INTO dbo.milestone (priority_id, name, status, planned_date, date_met, "
                 "owner_label, evidence_url, sort_order, active_flag) VALUES "
                 "(%s, %s, %s, %s, %s, %s, %s, %d, %d);"
                 % (_s(apri), _s(m["Name"]), _s(m["Status"]), _d(m["PlannedDate"]),
                    _d(m["DateMet"]), _s(m["OwnerLabel"]), _s(m["EvidenceURL"]),
                    m["SortOrder"], m["IsActive"]))
    L.append("GO")

    # -----------------------------------------------------------------------
    # 009 team layer: backfill the register's richer initiative fields.
    # -----------------------------------------------------------------------
    L.append("\n-- Team-layer fields on the D-1 initiatives (009_team_layer.sql).")
    for k in con.execute(
            "SELECT (COALESCE(MIId, Code)) AS Key_, TeamID, SourceAreaID, StrategyAlign, "
            "       Initiatives, ProposedTarget, TargetStatus FROM TeamInitiatives "
            "WHERE IsActive = 1 ORDER BY MIId"):
        iid = "INI-" + k["Key_"]
        team = _s("TEAM-%d" % k["TeamID"]) if k["TeamID"] else "NULL"
        area_name = con.execute("SELECT Name FROM SourceAreas WHERE SourceAreaID = ?",
                                 (k["SourceAreaID"],)).fetchone()
        area = "(SELECT source_area_id FROM dbo.source_area WHERE name = %s)" \
               % _s(area_name[0]) if (k["SourceAreaID"] and area_name) else "NULL"
        L.append("UPDATE dbo.initiative SET team_id = %s, source_area_id = %s, "
                 "strategy_align = %s, initiatives_text = %s, proposed_target = %s, "
                 "target_status = %s WHERE initiative_id = %s;"
                 % (team, area, _s(k["StrategyAlign"]), _s(k["Initiatives"]),
                    _s(k["ProposedTarget"]), _s(k["TargetStatus"]), _s(iid)))
    L.append("GO")

    L.append("PRINT 'Rev2 seed applied.';")
    L.append("GO")

    text = "\n".join(L) + "\n"
    if "--check" in sys.argv:
        cur = io.open(out, encoding="utf-8").read() if os.path.exists(out) else ""
        if cur != text:
            print("seed_rev2.sql is STALE; re-run without --check")
            return 1
        print("seed_rev2.sql is current")
        return 0
    io.open(out, "w", encoding="utf-8", newline="\n").write(text)
    print("wrote %s" % out)
    return 0


if __name__ == "__main__":
    raise SystemExit(build())
