"""Generate seed SQL for the organizational layer from the Dean's prototype.

Source of truth: the prototype's own `data.js`, read directly rather than
retyped, so the seed and the prototype cannot drift. Emits SQL that
`build_db.py`'s seed already includes by reference.

Run:  python db/build_team_layer.py            # writes db/seed_team_layer.sql
"""
import io
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
PROTO = os.path.join(os.path.expanduser("~"), "Documents",
                     "dean-prototype-data.js")
OUT = os.path.join(HERE, "seed_team_layer.sql")

# The prototype's data.js, fetched to temp during the redesign. Not in the repo
# (it is the Dean's artifact); the path is passed in or defaulted to temp.
DEFAULT_SRC = os.path.join(os.environ.get("TEMP", "/tmp"), "opencode",
                           "dean-proto", "data.js")


def _read(path):
    return io.open(path, encoding="utf-8").read()


def _sq(s):
    """SQL-quote a string, or NULL."""
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def parse_source_areas(t):
    m = re.search(r"const SOURCE_AREAS = \[(.*?)\];", t, re.S)
    return re.findall(r'"([^"]+)"', m.group(1))


def parse_teams(t):
    m = re.search(r"const AREAS = \[(.*?)\];", t, re.S)
    teams = re.findall(r'"([^"]+)"', m.group(1))
    d = re.search(r"const TEAM_DESCRIPTIONS = \{(.*?)\};", t, re.S).group(1)
    desc = dict(re.findall(r'"([^"]+)":\s*"([^"]+)"', d))
    return [(name, desc.get(name, "")) for name in teams]


def parse_priorities(t):
    m = re.search(r"const PRIORITIES = \[(.*?)\n\];", t, re.S)
    body = m.group(1)
    out = []
    for blk in re.findall(r"\{(.*?)\}", body, re.S):
        def field(k):
            mm = re.search(r'%s:\s*"((?:[^"\\]|\\.)*)"' % k, blk, re.S)
            return mm.group(1) if mm else None
        out.append({
            "code": field("code"), "title": field("title"), "short": field("short"),
            "description": field("description"), "measure": field("measure"),
            "target": field("target"), "cadence": field("cadence"),
            "owner": field("owner"), "color": field("color"),
        })
    return out


def parse_goals(t):
    """The 29 Major Initiatives, from the goal() factory calls."""
    calls = re.findall(
        r'goal\(SOURCE_AREAS\[(\d+)\],\s*"(\d+)",\s*"((?:[^"\\]|\\.)*)",\s*'
        r'"((?:[^"\\]|\\.)*)",\s*"((?:[^"\\]|\\.)*)",\s*'
        r'(null|"(?:[^"\\]|\\.)*"),\s*(\d+),\s*\[([^\]]*)\](?:,\s*'
        r'(null|"(?:[^"\\]|\\.)*")(?:,\s*"(?:[^"\\]|\\.)*")?)?\)', t, re.S)
    out = []
    for area_i, num, title, strategy, initiatives, target, slide, prios, proposed in calls:
        def unq(s):
            if s == "null":
                return None
            return s.strip('"')
        out.append({
            "code": "%s-%s" % (int(area_i) + 1, num),
            "areaIndex": int(area_i),
            "title": title, "strategy": strategy, "initiatives": initiatives,
            # `target` (the prototype's sourceTarget) was always equal to the
            # proposed target or empty, so only one target is kept. `slide` is a
            # deck slide number the canon does not have, so it is dropped too.
            "priorities": re.findall(r'"([^"]+)"', prios),
            "proposedTarget": unq(proposed) or unq(target),
            "targetStatus": "source" if unq(target) else "needs_review",
        })
    return out


def build(src=DEFAULT_SRC):
    t = _read(src)
    areas = parse_source_areas(t)
    teams = parse_teams(t)
    priorities = parse_priorities(t)
    goals = parse_goals(t)

    L = ["-- GENERATED by db/build_team_layer.py from the Dean's prototype data.js.",
         "-- Do not hand-edit; change the generator.",
         "",
         "-- Source areas (5)",
         "INSERT INTO SourceAreas (Name) VALUES"]
    L.append(",\n".join("  (%s)" % _sq(a) for a in areas) + ";")
    L.append("")
    L.append("-- Teams (4)")
    L.append("INSERT INTO Teams (Name, Description) VALUES")
    L.append(",\n".join("  (%s, %s)" % (_sq(n), _sq(d)) for n, d in teams) + ";")
    L.append("")
    L.append("-- The four governed priority fields the schema did not hold.")
    # The database names the priorities by SHORT name (Identity, Innovation, ...);
    # the prototype names them by code (P01..). Map code -> the database's name,
    # using the 6/6 mapping recorded in deans-prototype-reading.md. Keying on the
    # code rather than the prototype's `short` is what makes this reliable - the
    # short strings differ ("Shared identity" vs "Identity").
    CODE_TO_DB_NAME = {
        "P01": "Identity", "P02": "Innovation", "P03": "Pathways",
        "P04": "Scale", "P05": "Data", "P06": "Culture",
    }
    for p in priorities:
        db_name = CODE_TO_DB_NAME.get(p["code"])
        if db_name is None:
            continue
        L.append(
            "UPDATE Priorities SET Code=%s, FullTitle=%s, Measure=%s, Target=%s, "
            "Cadence=%s, OwnerLabel=%s, Colour=%s, Description=COALESCE(Description, %s) "
            "WHERE PriorityName=%s;"
            % (_sq(p["code"]), _sq(p["title"]), _sq(p["measure"]),
               _sq(p["target"]), _sq(p["cadence"]), _sq(p["owner"]),
               _sq(p["color"]), _sq(p["description"]), _sq(db_name)))
    L.append("")
    L.append("-- The 29 Major Initiatives")
    L.append("INSERT INTO MajorInitiatives (Code, Title, TeamID, SourceAreaID, StrategyAlign, "
             "Initiatives, ProposedTarget, TargetStatus) VALUES")
    vals = []
    for g in goals:
        # Team is assigned per-initiative in the prototype (TEAM_ASSIGNMENTS); the
        # generator resolves it to the team's row id by name.
        team = _team_for(g["code"], t)
        vals.append("  (%s, %s, (SELECT TeamID FROM Teams WHERE Name=%s), "
                    "(SELECT SourceAreaID FROM SourceAreas WHERE Name=%s), "
                    "%s, %s, %s, %s)"
                    % (_sq(g["code"]), _sq(g["title"]), _sq(team), _sq(areas[g["areaIndex"]]),
                       _sq(g["strategy"]), _sq(g["initiatives"]),
                       _sq(g["proposedTarget"]), _sq(g["targetStatus"])))
    L.append(",\n".join(vals) + ";")
    L.append("")
    L.append("-- Which priorities each Major Initiative feeds")
    L.append("INSERT INTO MajorInitiativePriorities (MajorInitiativeID, PriorityID) VALUES")
    # The prototype's `priorities` array holds its internal ids ("pathways",
    # "data", ...), which map onto the database's short names by capitalising -
    # except where they differ. Resolve through the same code map.
    PROTOTYPE_ID_TO_DB = {
        "identity": "Identity", "innovation": "Innovation", "pathways": "Pathways",
        "quality": "Scale", "data": "Data", "culture": "Culture",
    }
    pvals = []
    for g in goals:
        for pr in g["priorities"]:
            db_name = PROTOTYPE_ID_TO_DB.get(pr.lower())
            if db_name is None:
                raise SystemExit("unmapped prototype priority id: %r" % pr)
            pvals.append("  ((SELECT MajorInitiativeID FROM MajorInitiatives WHERE Code=%s), "
                         "(SELECT PriorityID FROM Priorities WHERE PriorityName=%s))"
                         % (_sq(g["code"]), _sq(db_name)))
    L.append(",\n".join(pvals) + ";")
    L.append("")

    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L))
    print("wrote %s" % OUT)
    print("  source areas: %d, teams: %d, priorities: %d, major initiatives: %d, links: %d"
          % (len(areas), len(teams), len(priorities), len(goals), len(pvals)))


def _team_for(code, t):
    """Resolve an initiative's team from TEAM_ASSIGNMENTS, falling back to a lookup."""
    m = re.search(r'const TEAM_ASSIGNMENTS = \{(.*?)\};', t, re.S)
    pairs = re.findall(r'"([\d-]+)":\s*AREAS\[(\d)\]', m.group(1))
    idx = {k: int(v) for k, v in pairs}
    teams = re.findall(r'"([^"]+)"', re.search(r"const AREAS = \[(.*?)\];", t, re.S).group(1))
    if code in idx:
        return teams[idx[code]]
    return teams[0]


if __name__ == "__main__":
    build()
