"""Generate db/seed_milestones.sql: the Milestones table, the priority outcome
state, and the dataset-provenance row.

    python db/build_milestones_seed.py           # writes db/seed_milestones.sql
    python db/build_milestones_seed.py --check   # fail if the output differs

WHY THIS DATA IS HERE AND MARKED 'mock'.

The real milestone content does not exist yet: the wireframe workbook supplies
only the data-REQUIREMENTS (rows A-07..A-17), no names, dates, owners or
statuses, and its Summary says "Blocking: no owners are named yet". The app must
not hardcode data, so the milestone rows are a SEED (in the database), not a
literal in application code, and the dataset is tagged provenance='mock' so the
Outcomes page labels it instead of presenting it as confirmed (plan D5).

The 18 milestones and their statuses are the wireframe's illustrative scaffold
(the values formerly in scripts/build_oct16_data.py), preserved so the Outcomes
layout can be reviewed. Two wireframe pseudo-statuses are normalised to the real
model: "Due Dec" and "Confirm" are NOT milestone statuses - the first is a due
date and the second an unconfirmed state - so they become 'Not started' with the
date (where known) in PlannedDate. The reached counts are unchanged by that.

Owner names and planned dates are deliberately left NULL: inventing them would
be the exact dishonesty this model exists to prevent. The intake fills them.
"""
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "seed_milestones.sql")

#: (priority_code, name, status, planned_date, sort) -- MOCK, see module docstring.
MILESTONES = [
    ("P01", "Message architecture approved", "Met", None, 1),
    ("P01", "Teams adopted (1 of 4)", "In progress", None, 2),
    ("P01", "First asset audit", "Not started", None, 3),
    ("P02", "RDI baseline complete", "Met", None, 1),
    ("P02", "Innovation call launched", "Met", None, 2),
    ("P02", "First stage-gate decisions", "Not started", "2026-12-31", 3),
    ("P03", "Unified approval process", "In progress", None, 1),
    ("P03", "First badged pathway", "In progress", None, 2),
    ("P03", "Mapping rule approved", "Met", None, 3),
    ("P04", "Quality standard approved", "Not started", None, 1),
    ("P04", "Reuse baseline", "In progress", None, 2),
    ("P04", "Build-time baseline", "Not started", None, 3),
    ("P05", "KPI definitions drafted", "Met", None, 1),
    ("P05", "College dashboard", "In progress", None, 2),
    ("P05", "Owners named", "Not started", None, 3),
    ("P06", "Target structure approved", "Not started", None, 1),
    ("P06", "Q1 learning reviews", "In progress", None, 2),
    ("P06", "Operating model template", "Met", None, 3),
]

#: priority_code -> (outcome status, last-updated). The reported state on the
#: Outcomes cards. Its own vocabulary (ADR-0002). MOCK.
OUTCOME_STATE = {
    "P01": ("On track", "2026-10-07"),
    "P02": ("On track", "2026-10-07"),
    "P03": ("At risk", "2026-10-07"),
    "P04": ("At risk", "2026-10-07"),
    "P05": ("On track", "2026-10-07"),
    "P06": ("On track", "2026-10-07"),
}


def _sq(s):
    return "NULL" if s is None else "'" + str(s).replace("'", "''") + "'"


def build(out=OUT):
    L = ["-- GENERATED by db/build_milestones_seed.py. Do not hand-edit.",
         "-- MOCK data: illustrative milestones pending the intake (see the",
         "-- generator's docstring). Provenance is tagged 'mock' below.", ""]

    L.append("-- Milestones: a checkable event per Priority (ADR-0001).")
    L.append("DELETE FROM Milestones;")
    L.append("INSERT INTO Milestones (PriorityCode, Name, Status, PlannedDate, SortOrder) VALUES")
    vals = []
    for code, name, status, planned, sort in MILESTONES:
        vals.append("  (%s, %s, %s, %s, %d)"
                    % (_sq(code), _sq(name), _sq(status), _sq(planned), sort))
    L.append(",\n".join(vals) + ";")
    L.append("")

    L.append("-- The reported outcome state per Priority (workbook A-05/A-06).")
    for code, (status, updated) in OUTCOME_STATE.items():
        L.append("UPDATE Priorities SET Status=%s, LastUpdated=%s WHERE Code=%s;"
                 % (_sq(status), _sq(updated), _sq(code)))
    L.append("")

    L.append("-- Dataset provenance: the importer overwrites this with 'confirmed'.")
    L.append("DELETE FROM AppMeta;")
    L.append("INSERT INTO AppMeta (Key, Value) VALUES")
    L.append("  ('dataset_provenance', 'mock'),")
    L.append("  ('dataset_source', 'seed: illustrative milestones for build/layout review');")
    L.append("")

    # Local roles (ADR-0005). Assignment is by the person's current state, so it
    # holds as the register changes: the dashboard admin, the Dean, and every
    # person accountable for a team are leads; everyone active is a viewer.
    L.append("-- Roles and their assignment (ADR-0005). App-local, not provider groups.")
    L.append("DELETE FROM PeopleRoles;")
    L.append("DELETE FROM Roles;")
    L.append("INSERT INTO Roles (RoleID, Name, Description) VALUES")
    L.append("  (1, 'admin', 'the dashboard team: edits everything'),")
    L.append("  (2, 'dean', 'the Dean: updates any initiative and the Dean layer'),")
    L.append("  (3, 'team_lead', 'accountable for a team: updates its initiatives'),")
    L.append("  (4, 'viewer', 'may read every page');")
    L.append("INSERT INTO PeopleRoles (PersonID, RoleID)")
    L.append("  SELECT PersonID, 1 FROM People WHERE IsAdmin = 1")
    L.append("  UNION SELECT PersonID, 2 FROM People WHERE lower(trim(COALESCE(Title,''))) = 'dean'")
    L.append("  UNION SELECT PersonID, 3 FROM People WHERE TeamID IS NOT NULL")
    L.append("  UNION SELECT PersonID, 4 FROM People WHERE IsActive = 1;")
    L.append("")

    text = "\n".join(L)
    if "--check" in sys.argv:
        cur = io.open(out, encoding="utf-8").read() if os.path.exists(out) else ""
        if cur != text:
            print("seed_milestones.sql is STALE; re-run without --check")
            return 1
        print("seed_milestones.sql is current (%d milestones)" % len(MILESTONES))
        return 0

    io.open(out, "w", encoding="utf-8", newline="\n").write(text)
    print("wrote %s (%d milestones, %d outcome states)"
          % (out, len(MILESTONES), len(OUTCOME_STATE)))
    return 0


if __name__ == "__main__":
    raise SystemExit(build())
