-- GENERATED by db/build_milestones_seed.py. Do not hand-edit.
-- MOCK data: illustrative milestones pending the intake (see the
-- generator's docstring). Provenance is tagged 'mock' below.

-- Milestones: a checkable event per Priority (ADR-0001). Keyed to the
-- Priorities ROW for this plan year, since the code recurs each year.
DELETE FROM Milestones;
INSERT INTO Milestones (PriorityID, Name, Status, PlannedDate, SortOrder) VALUES
  ((SELECT PriorityID FROM Priorities WHERE Code='P01' AND PlanYear=2027), 'Message architecture approved', 'Met', NULL, 1),
  ((SELECT PriorityID FROM Priorities WHERE Code='P01' AND PlanYear=2027), 'Teams adopted (1 of 4)', 'In progress', NULL, 2),
  ((SELECT PriorityID FROM Priorities WHERE Code='P01' AND PlanYear=2027), 'First asset audit', 'Not started', NULL, 3),
  ((SELECT PriorityID FROM Priorities WHERE Code='P02' AND PlanYear=2027), 'RDI baseline complete', 'Met', NULL, 1),
  ((SELECT PriorityID FROM Priorities WHERE Code='P02' AND PlanYear=2027), 'Innovation call launched', 'Met', NULL, 2),
  ((SELECT PriorityID FROM Priorities WHERE Code='P02' AND PlanYear=2027), 'First stage-gate decisions', 'Not started', '2026-12-31', 3),
  ((SELECT PriorityID FROM Priorities WHERE Code='P03' AND PlanYear=2027), 'Unified approval process', 'In progress', NULL, 1),
  ((SELECT PriorityID FROM Priorities WHERE Code='P03' AND PlanYear=2027), 'First badged pathway', 'In progress', NULL, 2),
  ((SELECT PriorityID FROM Priorities WHERE Code='P03' AND PlanYear=2027), 'Mapping rule approved', 'Met', NULL, 3),
  ((SELECT PriorityID FROM Priorities WHERE Code='P04' AND PlanYear=2027), 'Quality standard approved', 'Not started', NULL, 1),
  ((SELECT PriorityID FROM Priorities WHERE Code='P04' AND PlanYear=2027), 'Reuse baseline', 'In progress', NULL, 2),
  ((SELECT PriorityID FROM Priorities WHERE Code='P04' AND PlanYear=2027), 'Build-time baseline', 'Not started', NULL, 3),
  ((SELECT PriorityID FROM Priorities WHERE Code='P05' AND PlanYear=2027), 'KPI definitions drafted', 'Met', NULL, 1),
  ((SELECT PriorityID FROM Priorities WHERE Code='P05' AND PlanYear=2027), 'College dashboard', 'In progress', NULL, 2),
  ((SELECT PriorityID FROM Priorities WHERE Code='P05' AND PlanYear=2027), 'Owners named', 'Not started', NULL, 3),
  ((SELECT PriorityID FROM Priorities WHERE Code='P06' AND PlanYear=2027), 'Target structure approved', 'Not started', NULL, 1),
  ((SELECT PriorityID FROM Priorities WHERE Code='P06' AND PlanYear=2027), 'Q1 learning reviews', 'In progress', NULL, 2),
  ((SELECT PriorityID FROM Priorities WHERE Code='P06' AND PlanYear=2027), 'Operating model template', 'Met', NULL, 3);

-- The reported outcome state per Priority (workbook A-05/A-06).
UPDATE Priorities SET Status='On track', LastUpdated='2026-10-07' WHERE Code='P01' AND PlanYear=2027;
UPDATE Priorities SET Status='On track', LastUpdated='2026-10-07' WHERE Code='P02' AND PlanYear=2027;
UPDATE Priorities SET Status='At risk', LastUpdated='2026-10-07' WHERE Code='P03' AND PlanYear=2027;
UPDATE Priorities SET Status='At risk', LastUpdated='2026-10-07' WHERE Code='P04' AND PlanYear=2027;
UPDATE Priorities SET Status='On track', LastUpdated='2026-10-07' WHERE Code='P05' AND PlanYear=2027;
UPDATE Priorities SET Status='On track', LastUpdated='2026-10-07' WHERE Code='P06' AND PlanYear=2027;

-- Dataset provenance: the importer overwrites this with 'confirmed'.
DELETE FROM AppMeta;
INSERT INTO AppMeta (Key, Value) VALUES
  ('dataset_provenance', 'mock'),
  ('dataset_source', 'seed: illustrative milestones for build/layout review'),
  ('current_plan_year', '2027');

-- Roles and their assignment (ADR-0005, DR-05, DR-23). App-local.
DELETE FROM PeopleRoles;
DELETE FROM Roles;
INSERT INTO Roles (RoleID, Name, Description) VALUES
  (1, 'PlatformAdmin', 'technical/application administration and approved access administration'),
  (2, 'ExecutiveSponsor', 'the Dean: portfolio read plus executive actions (never routine data edits)'),
  (3, 'DataOwner', 'governs portfolio data: approvals, exceptions, quality, accountability'),
  (4, 'Operator', 'Strategic Operations: portfolio and data maintenance'),
  (5, 'Contributor', 'edits assigned initiatives (future phase; unassigned initially)'),
  (6, 'Viewer', 'reads published content'),
  (7, 'TechnicalAdmin', 'OIT/Azure infrastructure support; platform health, not portfolio data');
-- Additional roster people (Strategic Operations, OIT support).
INSERT INTO People (PersonID, Name, Title, Email, IsActive) VALUES (8, 'Cassie Parkin', 'Strategic Operations', 'cparkin6@gatech.edu', 1) ON CONFLICT(PersonID) DO UPDATE SET Name=excluded.Name, Title=excluded.Title, Email=excluded.Email, IsActive=1;
INSERT INTO People (PersonID, Name, Title, Email, IsActive) VALUES (9, 'Chris Reyes', 'Strategic Operations', 'creyes39@gatech.edu', 1) ON CONFLICT(PersonID) DO UPDATE SET Name=excluded.Name, Title=excluded.Title, Email=excluded.Email, IsActive=1;
INSERT INTO People (PersonID, Name, Title, Email, IsActive) VALUES (10, 'DeMarco Williams', 'Strategic Operations', 'dwilliams406@gatech.edu', 1) ON CONFLICT(PersonID) DO UPDATE SET Name=excluded.Name, Title=excluded.Title, Email=excluded.Email, IsActive=1;
INSERT INTO People (PersonID, Name, Title, Email, IsActive) VALUES (11, 'Mike Sewell', 'OIT Technical Contact', 'msewell7@gatech.edu', 1) ON CONFLICT(PersonID) DO UPDATE SET Name=excluded.Name, Title=excluded.Title, Email=excluded.Email, IsActive=1;
-- Emails for the register people (roster).
UPDATE People SET Email='wgaudelli3@gatech.edu' WHERE Name='Bill Gaudelli';
UPDATE People SET Email='esmith460@gatech.edu' WHERE Name='Elizabeth Smith';
UPDATE People SET Email='tjacobbe3@gatech.edu' WHERE Name='Tim Jacobbe';
UPDATE People SET Email='mherane3@gatech.edu' WHERE Name='Mario Herane';
UPDATE People SET Email='ma128@gatech.edu' WHERE Name='Meltem Alemdar';
UPDATE People SET Email='eflavin6@gatech.edu' WHERE Name='Grace Flavin';
UPDATE People SET Email='kwong318@gatech.edu' WHERE Name='Kevin';
-- Explicit role assignment (a roster, not a heuristic).
INSERT INTO PeopleRoles (PersonID, RoleID) VALUES
  ((SELECT PersonID FROM People WHERE Name='Kevin'), (SELECT RoleID FROM Roles WHERE Name='PlatformAdmin')),
  ((SELECT PersonID FROM People WHERE Name='Kevin'), (SELECT RoleID FROM Roles WHERE Name='Operator')),
  ((SELECT PersonID FROM People WHERE Name='Kevin'), (SELECT RoleID FROM Roles WHERE Name='Viewer')),
  ((SELECT PersonID FROM People WHERE Name='Cassie Parkin'), (SELECT RoleID FROM Roles WHERE Name='PlatformAdmin')),
  ((SELECT PersonID FROM People WHERE Name='Cassie Parkin'), (SELECT RoleID FROM Roles WHERE Name='Operator')),
  ((SELECT PersonID FROM People WHERE Name='Cassie Parkin'), (SELECT RoleID FROM Roles WHERE Name='Viewer')),
  ((SELECT PersonID FROM People WHERE Name='Chris Reyes'), (SELECT RoleID FROM Roles WHERE Name='PlatformAdmin')),
  ((SELECT PersonID FROM People WHERE Name='Chris Reyes'), (SELECT RoleID FROM Roles WHERE Name='Operator')),
  ((SELECT PersonID FROM People WHERE Name='Chris Reyes'), (SELECT RoleID FROM Roles WHERE Name='Viewer')),
  ((SELECT PersonID FROM People WHERE Name='DeMarco Williams'), (SELECT RoleID FROM Roles WHERE Name='PlatformAdmin')),
  ((SELECT PersonID FROM People WHERE Name='DeMarco Williams'), (SELECT RoleID FROM Roles WHERE Name='Operator')),
  ((SELECT PersonID FROM People WHERE Name='DeMarco Williams'), (SELECT RoleID FROM Roles WHERE Name='Viewer')),
  ((SELECT PersonID FROM People WHERE Name='Elizabeth Smith'), (SELECT RoleID FROM Roles WHERE Name='DataOwner')),
  ((SELECT PersonID FROM People WHERE Name='Elizabeth Smith'), (SELECT RoleID FROM Roles WHERE Name='Viewer')),
  ((SELECT PersonID FROM People WHERE Name='Bill Gaudelli'), (SELECT RoleID FROM Roles WHERE Name='ExecutiveSponsor')),
  ((SELECT PersonID FROM People WHERE Name='Bill Gaudelli'), (SELECT RoleID FROM Roles WHERE Name='Viewer')),
  ((SELECT PersonID FROM People WHERE Name='Grace Flavin'), (SELECT RoleID FROM Roles WHERE Name='Viewer')),
  ((SELECT PersonID FROM People WHERE Name='Mario Herane'), (SELECT RoleID FROM Roles WHERE Name='Viewer')),
  ((SELECT PersonID FROM People WHERE Name='Meltem Alemdar'), (SELECT RoleID FROM Roles WHERE Name='Viewer')),
  ((SELECT PersonID FROM People WHERE Name='Tim Jacobbe'), (SELECT RoleID FROM Roles WHERE Name='Viewer')),
  ((SELECT PersonID FROM People WHERE Name='Mike Sewell'), (SELECT RoleID FROM Roles WHERE Name='TechnicalAdmin')),
  ((SELECT PersonID FROM People WHERE Name='Mike Sewell'), (SELECT RoleID FROM Roles WHERE Name='Viewer'));
