-- =====================================================================
-- SAMPLE / BASE DATA — the lookup rows the register seed builds on.
--
-- After the 2026-10-07 merge there is ONE initiative model: the register's
-- `MajorInitiatives` (29 rows), seeded by `seed_team_layer.sql`,
-- `seed_canon_links.sql` and `seed_register.sql`. The prototype's sample
-- `Initiatives` and its diary were removed here.
--
-- This file now seeds only the shared lookups the register seed references:
-- the five Strategy 2035 goals, the six 2027 priorities (names only; their
-- governed fields are set by seed_team_layer.sql), and the People rows the
-- register seed then overwrites with real names.
-- =====================================================================

PRAGMA foreign_keys = ON;

-- Goals. Wording is CANONICAL and comes from the Strategy 2035 deck, slide 7
-- ("College Goals: How We Will Advance Our Vision"). Generated by
-- scripts/extract_canonical_goals.py into db/canonical_goals.py, not typed.
--
-- Corrected 2026-10-07: this block previously had goals 3 and 4 transposed
-- (Research at 3 where the deck has Learner, Learner impact at 4 where the deck
-- has Research), goal 1 as a truncated paraphrase, and no title at all for goals
-- 2-5. A goal's number is its identity, so this was fixed by re-seeding from the
-- source rather than by editing numbers in place - editing a number would move
-- the initiatives tagged to it.
INSERT INTO Goals (GoalNumber, ShortName, FullName) VALUES
 (1, 'Academic', 'Catalyze a learning society and build the world’s home for transformative learning systems leaders.'),
 (2, 'Extension', 'Empower communities with limitless learning and scale our extension model for global impact.'),
 (3, 'Learner', 'Engage 5 million learners with Georgia Tech–designed lifetime learning touchpoints.'),
 (4, 'Research', 'Be the global thought leader in optimized learning systems.'),
 (5, 'Operational', 'Revolutionize an operational model that is seamless, data-rich, proactive, and delivers a learner-first experience.');

-- 2027 annual priorities (names only; seed_team_layer.sql adds the governed
-- fields - measure, target, cadence, owner.)
INSERT INTO Priorities (PriorityName, PlanYear) VALUES
 ('Culture',2027),('Scale',2027),('Identity',2027),
 ('Innovation',2027),('Pathways',2027),('Data',2027);

-- Placeholder people. seed_register.sql OVERWRITES ids 1-4 with the register's
-- named owners and INSERTs the rest; PersonID 5 (Kevin, the dashboard admin)
-- stays. Kept here so the register seed's People upsert has rows to target.
INSERT INTO People (PersonID, Name, Title, ReportsToID) VALUES
 (1, 'Bill',      'Dean', NULL),
 (2, 'Elizabeth', NULL, 1),
 (3, 'Tim',       NULL, 1),
 (4, 'Mario',     NULL, 1);

-- Dashboard team admin (can edit everything; owns no initiative).
INSERT INTO People (PersonID, Name, Title, ReportsToID, IsAdmin) VALUES
 (5, 'Kevin', 'Associate Director, Strategic Operations', NULL, 1);
