-- GENERATED by db/build_milestone_clauses_seed.py. Do not hand-edit.
--
-- One milestone per semicolon-delimited clause of the register's column F,
-- "FY2027 Target / Achievement Marks". 84 clauses across 29 initiatives.
-- Clause text is VERBATIM from the register.
--
-- WeightBasis records how each weight was derived and WeightSource is
-- 'inferred' throughout: no human has confirmed these yet. See the
-- generator's docstring. NeedsRewrite flags the 12 clauses that are not
-- checkable events by the schema's own definition.

DELETE FROM Milestones;

-- 1-02  Reusable content
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='1-02' AND PlanYear=2027), 2027, 1, 'More than 1,000 approved objects', NULL, NULL, 0.5000000000, 'headline-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='1-02' AND PlanYear=2027), 2027, 2, 'at least 20% reuse', NULL, NULL, 0.2500000000, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='1-02' AND PlanYear=2027), 2027, 3, 'non-degree development average of 28 days or less', NULL, NULL, 0.2500000000, 'support-quant', 'inferred', 0);

-- 1-03  Data, EdTech & Infinity
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='1-03' AND PlanYear=2027), 2027, 1, 'Infinity 2.0 public launch', NULL, NULL, 0.5151515152, 'headline-gate', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='1-03' AND PlanYear=2027), 2027, 2, '3 data domains connected', NULL, NULL, 0.3030303030, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='1-03' AND PlanYear=2027), 2027, 3, 'personalized journey', NULL, NULL, 0.1818181818, 'support-soft', 'inferred', 1);

-- 3-01  Growth Engine Readiness
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='3-01' AND PlanYear=2027), 2027, 1, 'B2B strategy launched', NULL, NULL, 0.5000000000, 'headline-soft', 'inferred', 1),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='3-01' AND PlanYear=2027), 2027, 2, 'tech-enabled operating model implemented', NULL, NULL, 0.2500000000, 'support-soft', 'inferred', 1),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='3-01' AND PlanYear=2027), 2027, 3, 'repeatable sales and strategic account management processes implemented', NULL, NULL, 0.2500000000, 'support-soft', 'inferred', 1);

-- 3-02  Strategic Partnership & Revenue Growth
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='3-02' AND PlanYear=2027), 2027, 1, '100+ qualified and engaged B2B leads', NULL, NULL, 0.4000000000, 'headline-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='3-02' AND PlanYear=2027), 2027, 2, '5+ new partners secured', NULL, NULL, 0.2000000000, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='3-02' AND PlanYear=2027), 2027, 3, '2+ new partners launched', NULL, NULL, 0.2000000000, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='3-02' AND PlanYear=2027), 2027, 4, '$1M+ ARR', NULL, NULL, 0.2000000000, 'support-quant', 'inferred', 0);

-- 3-03  Geographic Expansion
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='3-03' AND PlanYear=2027), 2027, 1, 'Scalable Atria business model established', NULL, NULL, 0.2500000000, 'headline-soft', 'inferred', 1),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='3-03' AND PlanYear=2027), 2027, 2, 'non-main-campus assets inventoried', NULL, NULL, 0.1250000000, 'support-soft', 'inferred', 1),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='3-03' AND PlanYear=2027), 2027, 3, '10 locations under exploration', NULL, NULL, 0.2083333333, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='3-03' AND PlanYear=2027), 2027, 4, '2 piloted', NULL, NULL, 0.2083333333, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='3-03' AND PlanYear=2027), 2027, 5, '2 new sites activated', NULL, NULL, 0.2083333333, 'support-quant', 'inferred', 0);

-- 3-04  Asset Utilization
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='3-04' AND PlanYear=2027), 2027, 1, 'Increase Peachtree Corners utilization by 25%+', NULL, NULL, 0.7692307692, 'headline-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='3-04' AND PlanYear=2027), 2027, 2, 'develop or advance the long-term Savannah strategy', NULL, NULL, 0.2307692308, 'support-soft', 'inferred', 1);

-- 1-01  Portfolio & pathways
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='1-01' AND PlanYear=2027), 2027, 1, 'At least 2 recognized pathways plus badges', NULL, NULL, 0.6250000000, 'headline-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='1-01' AND PlanYear=2027), 2027, 2, 'AI and Durable Skills', NULL, NULL, 0.1875000000, 'support-soft', 'inferred', 1),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='1-01' AND PlanYear=2027), 2027, 3, 'market and financial analysis', NULL, NULL, 0.1875000000, 'support-soft', 'inferred', 1);

-- 5-01  Establish and Implement Faculty Governance Process
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-01' AND PlanYear=2027), 2027, 1, 'Approve the faculty governance charter and process by Q1', NULL, 1, 0.6296296296, 'headline-gate', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-01' AND PlanYear=2027), 2027, 2, 'route 100% of applicable faculty actions through it by Q3.', NULL, 3, 0.3703703704, 'support-quant', 'inferred', 0);

-- 5-02  Develop and Implement a Faculty Evaluation and Promotion System
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-02' AND PlanYear=2027), 2027, 1, 'Approve the evaluation and promotion framework by Q2', NULL, 2, 0.4788732394, 'headline-gate', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-02' AND PlanYear=2027), 2027, 2, 'orient 100% of eligible faculty', NULL, NULL, 0.2816901408, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-02' AND PlanYear=2027), 2027, 3, 'complete one pilot cycle and incorporate feedback.', NULL, NULL, 0.2394366197, 'support-gate', 'inferred', 0);

-- 5-03  Develop approval/governance process for academic programs and digital credentials
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-03' AND PlanYear=2027), 2027, 1, 'Launch one approval process for credit, non-credit, and digital credentials by Q2', NULL, 2, 0.4594594595, 'headline-gate', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-03' AND PlanYear=2027), 2027, 2, 'route 100% of new offerings through it', NULL, NULL, 0.2702702703, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-03' AND PlanYear=2027), 2027, 3, 'reach a median decision time of 45 days or less.', NULL, NULL, 0.2702702703, 'support-quant', 'inferred', 0);

-- 5-04  Fill open-rank faculty positions and align faculty work with Strategy 2035
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-04' AND PlanYear=2027), 2027, 1, 'Fill 100% of authorized FY2027 faculty searches', NULL, NULL, 0.5194805195, 'headline-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-04' AND PlanYear=2027), 2027, 2, 'align 90-day plans for all new hires to Strategy 2035', NULL, NULL, 0.2597402597, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-04' AND PlanYear=2027), 2027, 3, 'establish mentoring plans for all continuing faculty.', NULL, NULL, 0.2207792208, 'support-gate', 'inferred', 0);

-- 5-05  Empower faculty to engage in innovative program development and align work functions
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-05' AND PlanYear=2027), 2027, 1, 'Complete faculty work-function reviews by Q2', NULL, 2, 0.4788732394, 'headline-gate', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-05' AND PlanYear=2027), 2027, 2, 'engage at least 75% of faculty in program innovation or research', NULL, NULL, 0.2816901408, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-05' AND PlanYear=2027), 2027, 3, 'document all redeployment decisions.', NULL, NULL, 0.2394366197, 'support-gate', 'inferred', 0);

-- 5-06  Grow the institute-wide faculty network engaged in CLL programs
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-06' AND PlanYear=2027), 2027, 1, 'Engage at least 25 faculty collaborators from at least 6 colleges', NULL, NULL, 0.6666666667, 'headline-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-06' AND PlanYear=2027), 2027, 2, 'secure contributions from at least 10 to CLL offerings or initiatives.', NULL, NULL, 0.3333333333, 'support-quant', 'inferred', 0);

-- 5-07  Recruit students into traditional academic programs
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-07' AND PlanYear=2027), 2027, 1, 'Approve program-level enrollment targets by Q1', NULL, 1, 0.4788732394, 'headline-gate', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-07' AND PlanYear=2027), 2027, 2, 'achieve at least 90% of the FY2027 enrollment plan', NULL, NULL, 0.2816901408, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-07' AND PlanYear=2027), 2027, 3, 'review yield and retention each term.', NULL, NULL, 0.2394366197, 'support-gate', 'inferred', 0);

-- 5-08  Stand up innovative traditional academic programs
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-08' AND PlanYear=2027), 2027, 1, 'Approve or launch at least 2 programs', NULL, NULL, 0.5000000000, 'headline-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-08' AND PlanYear=2027), 2027, 2, 'move 3 additional concepts through market and academic review', NULL, NULL, 0.2500000000, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-08' AND PlanYear=2027), 2027, 3, 'meet at least 90% of approved milestones.', NULL, NULL, 0.2500000000, 'support-quant', 'inferred', 0);

-- 5-09  Build coursework as reusable learning experiences
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-09' AND PlanYear=2027), 2027, 1, 'Build 100% of new coursework as reusable learning modules', NULL, NULL, 0.5555555556, 'headline-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-09' AND PlanYear=2027), 2027, 2, 'achieve at least 20% reuse across offerings', NULL, NULL, 0.2777777778, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='5-09' AND PlanYear=2027), 2027, 3, 'apply metadata and quality standards to every module.', NULL, NULL, 0.1666666667, 'support-soft', 'inferred', 1);

-- 4-01  RDI Baseline & Dashboard
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='4-01' AND PlanYear=2027), 2027, 1, 'Complete the RDI baseline by Q1', NULL, 1, 0.4788732394, 'headline-gate', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='4-01' AND PlanYear=2027), 2027, 2, 'capture 100% of active RDI projects', NULL, NULL, 0.2816901408, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='4-01' AND PlanYear=2027), 2027, 3, 'publish a quarterly dashboard beginning in Q2.', NULL, NULL, 0.2394366197, 'support-gate', 'inferred', 0);

-- 4-02  Research & Innovation Agenda
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='4-02' AND PlanYear=2027), 2027, 1, 'Approve 3–5 research and innovation themes by Q1', NULL, 1, 0.5000000000, 'headline-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='4-02' AND PlanYear=2027), 2027, 2, 'map 100% of priority investments', NULL, NULL, 0.2500000000, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='4-02' AND PlanYear=2027), 2027, 3, 'activate at least 2 cross-unit collaborations.', NULL, NULL, 0.2500000000, 'support-quant', 'inferred', 0);

-- 4-03  Research & Innovation Capacity & Infrastructure
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='4-03' AND PlanYear=2027), 2027, 1, 'Approve a roles, funding, tools, and infrastructure plan by Q2', NULL, 2, 0.6296296296, 'headline-gate', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='4-03' AND PlanYear=2027), 2027, 2, 'resolve at least 80% of critical capacity gaps by Q4.', NULL, 4, 0.3703703704, 'support-quant', 'inferred', 0);

-- 4-04  Research & Innovation Mechanism
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='4-04' AND PlanYear=2027), 2027, 1, 'Launch at least 2 innovation mechanisms or calls', NULL, NULL, 0.5000000000, 'headline-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='4-04' AND PlanYear=2027), 2027, 2, 'initiate 6 pilots', NULL, NULL, 0.2500000000, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='4-04' AND PlanYear=2027), 2027, 3, 'complete stage-gate reviews for 100% and at least 3 scale, adapt, or stop decisions.', NULL, NULL, 0.2500000000, 'support-quant', 'inferred', 0);

-- 4-05  CLL Learning & Impact Measures
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='4-05' AND PlanYear=2027), 2027, 1, 'Approve a core learning and impact measure set by Q2', NULL, 2, 0.4788732394, 'headline-gate', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='4-05' AND PlanYear=2027), 2027, 2, 'instrument at least 80% of priority offerings', NULL, NULL, 0.2816901408, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='4-05' AND PlanYear=2027), 2027, 3, 'publish quarterly impact results.', NULL, NULL, 0.2394366197, 'support-gate', 'inferred', 0);

-- 4-06  Learning Studio/Makerspace Model
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='4-06' AND PlanYear=2027), 2027, 1, 'Approve the operating model and business case by Q2', NULL, 2, 0.6296296296, 'headline-gate', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='4-06' AND PlanYear=2027), 2027, 2, 'run at least 3 pilots with 150 participants and at least 80% participant satisfaction.', NULL, NULL, 0.3703703704, 'support-quant', 'inferred', 0);

-- 1-04  Team operating models
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='1-04' AND PlanYear=2027), 2027, 1, '100% of units', NULL, NULL, 0.7692307692, 'headline-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='1-04' AND PlanYear=2027), 2027, 2, 'new models documented, approved, and tested', NULL, NULL, 0.2307692308, 'support-soft', 'inferred', 1);

-- 2-01  Financial, Operational, and Initiative Dashboards
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='2-01' AND PlanYear=2027), 2027, 1, 'One college dashboard and 4 team dashboards live by Q2', NULL, 2, 0.5194805195, 'headline-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='2-01' AND PlanYear=2027), 2027, 2, 'monthly review held', NULL, NULL, 0.2207792208, 'support-gate', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='2-01' AND PlanYear=2027), 2027, 3, 'data refreshed within 10 business days of period close.', NULL, NULL, 0.2597402597, 'support-quant', 'inferred', 0);

-- 2-02  Unified branding and messaging frameworks
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='2-02' AND PlanYear=2027), 2027, 1, 'Message architecture approved by Q1', NULL, 1, 0.3750000000, 'headline-soft', 'inferred', 1),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='2-02' AND PlanYear=2027), 2027, 2, 'all 4 teams implement by Q3', NULL, 3, 0.3125000000, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='2-02' AND PlanYear=2027), 2027, 3, 'at least 90% of reviewed public-facing assets align by Q4.', NULL, 4, 0.3125000000, 'support-quant', 'inferred', 0);

-- 2-03  Centralized Process & Procedure workflows
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='2-03' AND PlanYear=2027), 2027, 1, 'Document the 10 highest-impact cross-college processes', NULL, NULL, 0.5000000000, 'headline-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='2-03' AND PlanYear=2027), 2027, 2, 'standardize at least 80% by Q3', NULL, 3, 0.2500000000, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='2-03' AND PlanYear=2027), 2027, 3, 'reduce median cycle time by 20% by Q4.', NULL, 4, 0.2500000000, 'support-quant', 'inferred', 0);

-- 2-04  Admin & Ops LLM Agent
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='2-04' AND PlanYear=2027), 2027, 1, 'Launch a governed MVP by Q2', NULL, 2, 0.4594594595, 'headline-gate', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='2-04' AND PlanYear=2027), 2027, 2, 'support 5 priority workflows by Q3', NULL, 3, 0.2702702703, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='2-04' AND PlanYear=2027), 2027, 3, 'achieve at least 80% user satisfaction in the pilot.', NULL, NULL, 0.2702702703, 'support-quant', 'inferred', 0);

-- 2-05  Build Organizational Learning Capability
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='2-05' AND PlanYear=2027), 2027, 1, 'All 4 teams run quarterly learning cycles', NULL, NULL, 0.5000000000, 'headline-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='2-05' AND PlanYear=2027), 2027, 2, 'at least 80% of priority-role staff participate', NULL, NULL, 0.2500000000, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='2-05' AND PlanYear=2027), 2027, 3, 'each team implements 2 capability improvements.', NULL, NULL, 0.2500000000, 'support-quant', 'inferred', 0);

-- 2-06  Optimized Org Structure & Resource Onboarding
INSERT INTO Milestones
    (TeamInitiativeID, PlanYear, SortOrder, Name, Measure,
     TargetQuarter, Weight, WeightBasis, WeightSource, NeedsRewrite)
VALUES
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='2-06' AND PlanYear=2027), 2027, 1, 'Approve the target organization by Q1', NULL, 1, 0.4594594595, 'headline-gate', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='2-06' AND PlanYear=2027), 2027, 2, 'map 100% of key roles', NULL, NULL, 0.2702702703, 'support-quant', 'inferred', 0),
  ((SELECT TeamInitiativeID FROM TeamInitiatives WHERE Code='2-06' AND PlanYear=2027), 2027, 3, 'reach at least 90% role clarity and 60 days or less to productivity for new hires.', NULL, NULL, 0.2702702703, 'support-quant', 'inferred', 0);
